
builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - -X "github.com/gomicro/probe/cmd.Version={{.Env.VERSION}}"

  goos:
    - darwin
    - windows
    - linux

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

dockers:
  -
    goos: linux

    goarch: amd64

    image_templates:
      - "gomicro/probe:latest"
      - "gomicro/probe:{{ .Env.VERSION }}"
